export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_FEATURED_PRODUCT = "SET_FEATURED_PRODUCT";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
export const SET_CART = "SET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
